language: python
env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=cov
matrix:
    allow_failures:
        - env: TOXENV=cov
        - env: TOXENV=sith
install:
    - pip install --quiet --use-mirrors tox
script:
    - sudo start ssh || echo "SSH service already running"
    - ssh-keygen -t rsa -f ~/.ssh/id_rsa -N "" -q
    - cat ~/.ssh/id_rsa.pub >>~/.ssh/authorized_keys
    - ssh-keyscan -t rsa localhost >>~/.ssh/known_hosts
    - tox
after_script:
    - if [ $TOXENV == "cov" ]; then
      pip install --quiet --use-mirrors coveralls;
      coveralls;
      fi
