redis:
    apt: redis-server
    pacman: redis
    yum: redis
uwsgi-build-tools:
    apt: build-essential python-dev
psycopg2-build-tools:
    apt: libpq-dev python-dev
postgresql: 
    apt: postgresql
pip: 
    apt: python-pip
nginx: 
    apt: nginx
