redis:
    apt: redis-server
    pacman: redis
    yum: redis
mongodb:
    apt: 
        name: mongodb-10gen
        repo: "deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen"
        pgp: 7F0CEB10
uwsgi-build-tools:
    apt: build-essential python-dev
psycopg2-build-tools:
    apt: libpq-dev python-dev
postgresql: 
    apt: postgresql
pip: 
    apt: python-pip
nginx: 
    apt: nginx
